/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LifeNotesIndexImport } from './routes/life-notes/index'
import { Route as HomeIndexImport } from './routes/home/index'

// Create/Update Routes

const LifeNotesIndexRoute = LifeNotesIndexImport.update({
  id: '/life-notes/',
  path: '/life-notes/',
  getParentRoute: () => rootRoute,
} as any)

const HomeIndexRoute = HomeIndexImport.update({
  id: '/home/',
  path: '/home/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/home/': {
      id: '/home/'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeIndexImport
      parentRoute: typeof rootRoute
    }
    '/life-notes/': {
      id: '/life-notes/'
      path: '/life-notes'
      fullPath: '/life-notes'
      preLoaderRoute: typeof LifeNotesIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/home': typeof HomeIndexRoute
  '/life-notes': typeof LifeNotesIndexRoute
}

export interface FileRoutesByTo {
  '/home': typeof HomeIndexRoute
  '/life-notes': typeof LifeNotesIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/home/': typeof HomeIndexRoute
  '/life-notes/': typeof LifeNotesIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/home' | '/life-notes'
  fileRoutesByTo: FileRoutesByTo
  to: '/home' | '/life-notes'
  id: '__root__' | '/home/' | '/life-notes/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  HomeIndexRoute: typeof HomeIndexRoute
  LifeNotesIndexRoute: typeof LifeNotesIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  HomeIndexRoute: HomeIndexRoute,
  LifeNotesIndexRoute: LifeNotesIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/home/",
        "/life-notes/"
      ]
    },
    "/home/": {
      "filePath": "home/index.tsx"
    },
    "/life-notes/": {
      "filePath": "life-notes/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
